version: 0.2.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - gh-pages
skip_tags: true
os: Visual Studio 2015
configuration: Release

install:
- nuget sources update -Name nuget.org -Source https://api.nuget.org/v3/index.json

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
